version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      actions-deps:
        patterns:
          - '@actions/*'
      dev-tools:
        patterns:
          - '@vercel/ncc'
          - 'typescript'
          - '@types/*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
